//! Cross-validation against Liang's algorithm on the bundled
//! `hyph-en-us.tex` pattern set.
//!
//! Each `(word, expected_breaks)` row was generated by running a
//! reference Python implementation of Liang's algorithm against the
//! exact same pattern file we vendor at
//! `crates/sigilbuzz-hyphen/patterns/en-us.txt`, with the canonical
//! `left = 2`, `right = 3` thresholds declared in the upstream
//! `.tex` source. This is *not* a comparison against pyphen — pyphen
//! ships a different (LibreOffice-derived) en-us dictionary whose
//! breaks differ from the classic Liang/Kuiken set.
//!
//! If sigilbuzz's Liang implementation drifts from the reference,
//! this test fails loudly with the offending word.

#![cfg(feature = "patterns-en-us")]

use sigilbuzz_hyphen::{hyphenate, Language, Patterns};

/// 50 common English words with their canonical Liang break offsets
/// against `hyph-en-us.tex` at `left=2, right=3`.
const CASES: &[(&str, &[usize])] = &[
    ("hyphenation", &[2, 6]),
    ("algorithm", &[2, 4]),
    ("computer", &[3]),
    ("programming", &[3, 7]),
    ("application", &[2, 5, 7]),
    ("language", &[3]),
    ("document", &[3, 4]),
    ("function", &[4]),
    ("parameter", &[2, 4, 6]),
    ("reference", &[3, 5]),
    ("standard", &[4]),
    ("character", &[4, 6]),
    ("encoding", &[2, 5]),
    ("parsing", &[4]),
    ("rendering", &[3, 6]),
    ("shaping", &[4]),
    ("glyph", &[]),
    ("font", &[]),
    ("kerning", &[4]),
    ("paragraph", &[4]),
    ("sentence", &[3]),
    ("database", &[4]),
    ("memory", &[3]),
    ("process", &[]),
    ("system", &[3]),
    ("network", &[3]),
    ("protocol", &[3, 5]),
    ("interface", &[2, 5]),
    ("project", &[3]),
    ("engineer", &[2, 4]),
    ("developer", &[2, 5]),
    ("architecture", &[2, 5, 8]),
    ("optimization", &[2, 4, 8]),
    ("benchmark", &[5]),
    ("parallel", &[3, 5]),
    ("concurrent", &[3, 6]),
    ("mutable", &[2, 4]),
    ("immutable", &[2]),
    ("iterator", &[2, 4, 5]),
    ("collection", &[3, 6]),
    ("beautiful", &[4, 6]),
    ("wonderful", &[3, 6]),
    ("university", &[3, 6]),
    ("mathematics", &[4, 5, 8]),
    ("philosophy", &[3, 6, 7]),
    ("literature", &[3, 5, 6]),
    ("television", &[4, 6]),
    ("continuous", &[3, 6, 7]),
    ("absolutely", &[2]),
    ("community", &[3, 5]),
];

#[test]
fn en_us_matches_canonical_liang() {
    let patterns = Patterns::for_language(Language::EnglishUs).unwrap();
    let mut mismatches: Vec<String> = Vec::new();
    for (word, expected) in CASES {
        let got = hyphenate(word, patterns);
        if got != *expected {
            mismatches.push(format!("  {word:>14}: expected {expected:?}, got {got:?}"));
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} of {} words diverged from the canonical Liang reference:\n{}",
        mismatches.len(),
        CASES.len(),
        mismatches.join("\n")
    );
}

#[test]
fn case_insensitive() {
    let patterns = Patterns::for_language(Language::EnglishUs).unwrap();
    let lower = hyphenate("hyphenation", patterns);
    let upper = hyphenate("HYPHENATION", patterns);
    let mixed = hyphenate("Hyphenation", patterns);
    assert_eq!(lower, upper);
    assert_eq!(lower, mixed);
}

#[test]
fn no_breaks_in_short_words() {
    let patterns = Patterns::for_language(Language::EnglishUs).unwrap();
    for word in ["a", "an", "the", "of", "is"] {
        assert!(
            hyphenate(word, patterns).is_empty(),
            "{word:?} should have no breaks"
        );
    }
}

#[test]
fn boundary_offsets_are_valid_byte_indices() {
    let patterns = Patterns::for_language(Language::EnglishUs).unwrap();
    for (word, _) in CASES {
        for off in hyphenate(word, patterns) {
            assert!(
                off > 0 && off < word.len(),
                "offset {off} out of bounds for {word:?}"
            );
            assert!(
                word.is_char_boundary(off),
                "offset {off} not a char boundary in {word:?}"
            );
        }
    }
}
